name: "Check and Build Docs"

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./"
        pre-build-command: pip install sphinx-rtd-theme recommonmark python-slugify && python -m management.json_to_md
        build-command: sphinx-build -b html . docs

    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/

    # Publish built docs to master branch.
    - name: Commit documentation changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        directory: docs
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
