name: "Check and Build Docs"

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./exercises/docs/"
        pre-build-command: pip install sphinx-rtd-theme
        build-command: sphinx-build -b html exercises/docs/ exercises/docs/html

    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: exercises/docs/html

    # Publish built docs to master branch.
    - name: Commit documentation changes
      run: |
        git clone https://github.com/mrgallo/python-exercises.git --branch gh-pages --single-branch gh-pages
        cp -r exercises/docs/html/* gh-pages
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
